variables:
  http_proxy: "http://http-proxy.sbb.spk-berlin.de:3128/"
  https_proxy: "http://http-proxy.sbb.spk-berlin.de:3128/"
  HTTP_PROXY: "http://http-proxy.sbb.spk-berlin.de:3128/"
  HTTPS_PROXY: "http://http-proxy.sbb.spk-berlin.de:3128/"

stages:
  - triggers

mirror:
  stage: triggers
  trigger:
    include: .gitlab/mirror.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
