stages:
  - pull

default:
  image: alpine

pull-gitlab:
  stage: pull
  script:
    - echo "This is redundant"

pull-github:
  stage: pull
  before_script:
    - apk add --no-cache git
  script:
    - git pull https://github.com/qurator-spk/dinglehopper.git
