name: test

on:
  push:
    branches:
      - master
  schedule:
    - cron: "00 16 07 * *"  # = monthly
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update pip
        run: python3 -m pip install -U pip
      - name: Install requirements*
        run: python3 -m pip install -r requirements*.txt

      - name: Test
        run: cd src && python3 -m pytest
